# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- "*"
- features/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- powershell: |
   
   $url ="http://validator.swagger.io/validator?url={$(System.DefaultWorkingDirectory)/OAS Keolis.Driver (2).yaml}"
   
   (curl $url).RawContentLength 

- powershell: |
    Add-Content -Path "$(System.DefaultWorkingDirectory)\testhtml.html" -Value "<img src='http://validator.swagger.io/validator?url={YOUR_URL}'>"

- task: RunARMTTKTests@1
  inputs:
    templatelocation: '$(System.DefaultWorkingDirectory)/azuredeploy.json'
    resultLocation: '$(System.DefaultWorkingDirectory)/'
    cliOutputResults: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/*-armttk.xml'
  condition: always()