trigger:
- master
- features/*
- fixes/*
- develop

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

steps:
- task: CmdLine@2
  displayName: 'Validate OpenAPI definition'
  inputs:
     script: |
        echo 'Cloning into sources folder at: $(Build.SourcesDirectory)'
        git clone https://github.com/char0n/swagger-editor-validate.git
        exit

