trigger:
- master
- features/*
- fixes/*
- develop

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'


- task: RunARMTTKTests@1
  inputs:
    templatelocation: '$(System.DefaultWorkingDirectory)/Deploy/*.json'
    resultLocation: '$(System.DefaultWorkingDirectory)/'
    cliOutputResults: true

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'NUnit'
    testResultsFiles: '$(System.DefaultWorkingDirectory)/*-armttk.xml'
  condition: always()

