trigger:
- master
- features/*
- fixes/*
- develop

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'
  URL_TO_VALIDATE: 'hello.file'

steps:
- task: CmdLine@2
  displayName: 'Validate OpenAPI definition'
  inputs:
     script: |
        echo 'Cloning into sources folder at: $(Build.SourcesDirectory)'
        git clone --branch=v2.0.0 https://github.com/swagger-api/validator-badge.git
        cd validator-badge
        mvn package -q -DskipTests=true -Dmaven.javadoc.skip=true -B -V jetty:run &
        cd ..
        sleep 60
        echo "Validating $(URL_TO_VALIDATE):"
        exit

